### ISSUE TITLE
 cls_token.pt vs IndexError: list index out of range error own custom dataset

### ISSUE THREAD

**Issue by chandagrover** [dogehhh/ReCLIP#8]
Dear Author,

How did you obtain cls_token.pt. 

I am trying to get the segmentation result on my custom dataset. I am able to produce psedo_labels using RECLIP model. when I am trying to train the model on my dataset with command: python tools/train.py --cfg 'config/xxx_train_ori_cfg.yaml' --model 'RECLIP', I am getting below error:

self.cls_token = torch.load('utils/cls_token.pt')
  0%|                                                                                                                                                | 0/73 [00:07<?, ?it/s]
Traceback (most recent call last):
  File "/usr/ReCLIP/tools/train.py", line 185, in <module>
    mp.spawn(train,
  File "/usr/ReCLIP/venv/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 282, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method="spawn")
  File "/usr/ReCLIP/venv/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 238, in start_processes
    while not context.join():
  File "/usr/ReCLIP/venv/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 189, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/usr/ReCLIP/venv/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 76, in _wrap
    fn(i, *args)
  File "/usr/ReCLIP/tools/train.py", line 117, in train
    for img, label, img_metas, filenames, pseudo_class in loop:
  File "/usr/ReCLIP/venv/lib/python3.9/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/usr/ReCLIP/venv/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/usr/ReCLIP/venv/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1344, in _next_data
    return self._process_data(data)
  File "/usr/ReCLIP/venv/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1370, in _process_data
    data.reraise()
  File "/usr/ReCLIP/venv/lib/python3.9/site-packages/torch/_utils.py", line 706, in reraise
    raise exception
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/ReCLIP/venv/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 309, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
  File "/usr/ReCLIP/venv/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/ReCLIP/venv/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 52, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/ReCLIP/tools/train.py", line 61, in __getitem__
    return img, label, img_metas, self.train_images[idx], self.pseudo_classes[idx]
IndexError: list index out of range

**Comment by dogehhh** [comment]
I obtain the cls token from the pre-trained CLIP model and put it in 'utils/cls_token.pt'.
I wonder whether your error comes from cls token, since there is another error named 'IndexError: list index out of range'.
